# Generated by Django 3.1.7 on 2022-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpmonthschedgrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=19, null=True)),
                ('source_code', models.CharField(blank=True, max_length=3, null=True)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('policy_no', models.CharField(blank=True, max_length=9, null=True)),
                ('group_tariff', models.CharField(blank=True, max_length=7, null=True)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('user_str', models.CharField(blank=True, max_length=15, null=True)),
                ('dola', models.DateField(blank=True, null=True)),
                ('account_year', models.IntegerField(blank=True, null=True)),
                ('account_month', models.IntegerField(blank=True, null=True)),
                ('chk_no', models.IntegerField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=1, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=10, null=True)),
                ('link_code', models.IntegerField(blank=True, null=True)),
                ('linked_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'corpmonthschedgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corpmonthsusp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=19, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=10, null=True)),
                ('trans_type', models.CharField(max_length=3)),
                ('ref_ref_no', models.CharField(blank=True, max_length=19, null=True)),
                ('ref_item_no', models.IntegerField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=1, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('account_month', models.IntegerField(blank=True, null=True)),
                ('account_year', models.IntegerField(blank=True, null=True)),
                ('dola', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('policy_no', models.CharField(blank=True, max_length=9, null=True)),
                ('source_code', models.CharField(blank=True, max_length=3, null=True)),
                ('group_tariff', models.CharField(blank=True, max_length=7, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_str', models.CharField(blank=True, max_length=15, null=True)),
                ('suspense_receipt_no', models.CharField(blank=True, max_length=10, null=True)),
                ('client_no', models.CharField(blank=True, max_length=8, null=True)),
                ('old_suspense_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'corpmonthsusp',
                'managed': False,
            },
        ),
    ]
