# Generated by Django 3.1.7 on 2022-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bnrclassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnr_code', models.CharField(blank=True, max_length=4, null=True)),
                ('bnr_descr', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'bnrclassification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_code', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sector_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cells',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countryparam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(blank=True, max_length=3, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('country_description', models.CharField(blank=True, max_length=60, null=True)),
                ('country_nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('bnr_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'countryparam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('district_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EconomicSubSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isic_code', models.CharField(blank=True, max_length=6, null=True)),
                ('isic_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'economic_sub_sectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glidentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.CharField(blank=True, max_length=24, null=True)),
                ('user1', models.CharField(blank=True, max_length=22, null=True)),
            ],
            options={
                'db_table': 'glidentity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glmasta',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desc_str', models.CharField(blank=True, max_length=20, null=True)),
                ('user1', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'glmasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('user_str', models.CharField(blank=True, max_length=33, null=True)),
            ],
            options={
                'db_table': 'glrelation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.IntegerField(blank=True, null=True)),
                ('status_desc', models.CharField(blank=True, max_length=20, null=True)),
                ('user1', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'glstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gltitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_code', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sp', models.CharField(blank=True, max_length=1, null=True)),
                ('user1', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 'gltitle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaicsCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naics_code', models.CharField(blank=True, max_length=6, null=True)),
                ('naics_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'NAICS_CODES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sp', models.CharField(blank=True, max_length=1, null=True)),
                ('user1', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 'occupation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.IntegerField(blank=True, null=True)),
                ('province_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=30, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_code', models.CharField(blank=True, max_length=10, null=True)),
                ('village_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sector_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('province_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'village',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnr_classification', models.CharField(blank=True, max_length=5, null=True)),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('sname', models.CharField(blank=True, max_length=50, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('resident_country', models.CharField(blank=True, max_length=10, null=True)),
                ('identity_type', models.CharField(blank=True, max_length=20, null=True)),
                ('identity_card_no', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=1, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('residence_type', models.CharField(blank=True, max_length=1, null=True)),
                ('occupation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('naics_code', models.CharField(blank=True, max_length=10, null=True)),
                ('economic_sub_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('relation_to_company_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pob_province', models.CharField(blank=True, max_length=50, null=True)),
                ('pob_district', models.CharField(blank=True, max_length=50, null=True)),
                ('pob_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('pob_cell', models.CharField(blank=True, max_length=50, null=True)),
                ('pob_village', models.CharField(blank=True, max_length=50, null=True)),
                ('rdb_reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rdb_reg_date', models.DateField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=20, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_position', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('town', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'ClientUpload',
            },
        ),
    ]
