from django.db import models

# Create your models here.

class Batchcode(models.Model):
    batch_type = models.CharField(max_length=3, primary_key=True)
    batch_serial = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'batchcode'

class Fobatch(models.Model):
    batch_no = models.CharField(max_length=8, primary_key=True)
    ref_no = models.CharField(max_length=19, blank=True, null=True)
    create_date = models.DateField(blank=True, null=True)
    uploaded_by = models.CharField(max_length=15, blank=True, null=True)
    uploaded_date = models.DateField(blank=True, null=True)
    approved_by = models.CharField(max_length=15, blank=True, null=True)
    approved_date = models.DateField(blank=True, null=True)
    posted_by = models.CharField(max_length=15, blank=True, null=True)
    posted_date = models.DateField(blank=True, null=True)
    no_of_recs = models.IntegerField(blank=True, null=True)
    total_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    batch_type = models.CharField(max_length=3, blank=True, null=True)
    approved = models.CharField(max_length=1, blank=True, null=True)
    posted = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'fobatch'


class Bankstateovpload(models.Model):
    ref_no = models.CharField(max_length=19, blank=True, null=True)
    item_no = models.IntegerField(blank=True, null=True)
    corporate_code = models.CharField(max_length=10, blank=True, null=True)
    source_code = models.CharField(max_length=3, blank=True, null=True)
    ovp_group = models.CharField(max_length=1, blank=True, null=True)
    grp_item_no = models.IntegerField(blank=True, null=True)
    group_tariff = models.CharField(max_length=7, blank=True, null=True)
    trans_date = models.DateField(blank=True, null=True)
    trans_amount = models.CharField(max_length=20, blank=True, null=True)
    client_name = models.CharField(max_length=100, blank=True, null=True)
    member_no = models.IntegerField(blank=True, null=True)
    payroll_no = models.CharField(max_length=10, blank=True, null=True)
    receipt_for = models.CharField(max_length=1, blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    proposal_no = models.IntegerField(blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'bankstateovpload'


class Corpmonth(models.Model):
    corporate_code = models.CharField(max_length=7, blank=True, null=True)
    ref_no = models.CharField(max_length=19, primary_key=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    statement_date = models.DateField(blank=True, null=True)
    statement_ref = models.CharField(max_length=20, blank=True, null=True)
    statement_amount = models.DecimalField(max_digits=20, decimal_places=2)
    dola = models.DateField(blank=True, null=True)
    user_str = models.CharField(max_length=15, blank=True, null=True)
    ovp_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    ovp_status = models.CharField(max_length=1, blank=True, null=True)
    ovp_receipt_no = models.CharField(max_length=10, blank=True, null=True)
    susp_status = models.CharField(max_length=1, blank=True, null=True)
    narration = models.CharField(max_length=160, blank=True, null=True)
    amount_in_words = models.CharField(max_length=150, blank=True, null=True)
    payee_name = models.CharField(max_length=45, blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'corpmonth'


class Lapol(models.Model):
    policy_no = models.CharField(max_length=9, primary_key=True)
    proposal_no = models.CharField(max_length=9, blank=True, null=True)
    proposal_date = models.DateField(blank=True, null=True)
    receipt_no = models.CharField(max_length=6, blank=True, null=True)
    branch = models.IntegerField(blank=True, null=True)
    account_type = models.IntegerField(blank=True, null=True)
    agent = models.IntegerField(blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    adb_extra = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    plan = models.CharField(max_length=2, blank=True, null=True)
    ltb_term = models.IntegerField(blank=True, null=True)
    pay_method = models.CharField(max_length=1, blank=True, null=True)
    pay_mode = models.CharField(max_length=1, blank=True, null=True)
    premdue_date = models.DateField(blank=True, null=True)
    amtprem_due = models.DecimalField(max_digits=17, decimal_places=2, blank=True, null=True)
    date_last_prem = models.DateField(blank=True, null=True)
    underwriters_code = models.CharField(max_length=3, blank=True, null=True)
    status_code = models.CharField(max_length=2, blank=True, null=True)
    effective_date = models.DateField(blank=True, null=True)
    maturity_date = models.DateField(blank=True, null=True)
    term_of_policy = models.IntegerField(blank=True, null=True)
    ltb_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    accrued_bonus = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    date_first_prem = models.DateField(blank=True, null=True)
    interim_bonus = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    adb_sum = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    min_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    sub_code = models.CharField(max_length=1, blank=True, null=True)
    decrease_sum = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    basic_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ltb_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    modal_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    adb_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    extra_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ltb_extra_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    waiver_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    policy_fees = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    received = models.DecimalField(max_digits=17, decimal_places=2, blank=True, null=True)
    pre_issued = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    main_susp = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    payment_suspense = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    odd_lot = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    prem_units = models.IntegerField(blank=True, null=True)
    life_cover = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    lifecvr_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    wp_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    adb_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    takeon_suspense = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    wp_extra_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    instal_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    nonsmoking_disc = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ltb_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    comm_payable = models.DecimalField(max_digits=17, decimal_places=2, blank=True, null=True)
    claim_notify_date = models.DateField(blank=True, null=True)
    reinstate_date = models.DateField(blank=True, null=True)
    cancell_date = models.DateField(blank=True, null=True)
    paidup_date = models.DateField(blank=True, null=True)
    paidup_charge = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    lapse_date = models.DateField(blank=True, null=True)
    issue_date = models.DateField(blank=True, null=True)
    alteration_date = models.DateField(blank=True, null=True)
    leb_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    joint_life = models.CharField(max_length=1, blank=True, null=True)
    loan_flag = models.CharField(max_length=1, blank=True, null=True)
    final_add_bonus = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    expected_premiums = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    extra_maturity_fees = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    mode_extra = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    maturity_penalty = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    payment = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surrender_date = models.DateField(blank=True, null=True)
    surrender_value = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    anniversary_prems = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    renewal_date = models.DateField(blank=True, null=True)
    loan_value = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    renewal_status = models.CharField(max_length=1, blank=True, null=True)
    comm_rate_yr1 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    comm_rate_yr2 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    comm_rate_yr3 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    add_comm_yr1 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    add_comm_yr2 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    add_comm_yr3 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    sup_code = models.CharField(max_length=3, blank=True, null=True)
    unit_no = models.IntegerField(blank=True, null=True)
    pay_period = models.IntegerField(blank=True, null=True)
    remark_code = models.CharField(max_length=2, blank=True, null=True)
    prev_status = models.CharField(max_length=2, blank=True, null=True)
    status_date = models.DateField(blank=True, null=True)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    creation_date = models.DateField(blank=True, null=True)
    creation_id = models.CharField(max_length=4, blank=True, null=True)
    debit_issue_date = models.DateField(blank=True, null=True)
    citizen_code = models.CharField(max_length=1, blank=True, null=True)
    bonus = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    lapse_charge = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    paidup_sum = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    exact_duration = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    suspense_date = models.DateField(blank=True, null=True)
    reinst_charge = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    interim_bon = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    last_claim_date = models.DateField(blank=True, null=True)
    claim_status = models.CharField(max_length=2, blank=True, null=True)
    settlement_date = models.DateField(blank=True, null=True)
    decline_date = models.DateField(blank=True, null=True)
    female_extra_prem = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    death_reason = models.CharField(max_length=1, blank=True, null=True)
    treaty_type = models.CharField(max_length=2, blank=True, null=True)
    persist_bonus = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    overide_comm = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    nof_premiums_due = models.IntegerField(blank=True, null=True)
    takeon_status = models.CharField(max_length=1, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    discount = models.CharField(max_length=1, blank=True, null=True)
    wp = models.CharField(max_length=1, blank=True, null=True)
    pa = models.CharField(max_length=1, blank=True, null=True)
    mortgage_protection = models.CharField(max_length=1, blank=True, null=True)
    over_rate_yr1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    over_rate_yr2 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    over_rate_yr3 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    supervisor_no = models.IntegerField(blank=True, null=True)
    bank_no = models.CharField(max_length=6, blank=True, null=True)
    claim_date = models.DateField(blank=True, null=True)
    lapse_process_date = models.DateField(blank=True, null=True)
    complete_partial_payment = models.IntegerField(blank=True, null=True)
    death_claim_acceptance = models.CharField(max_length=1, blank=True, null=True)
    death_date = models.DateField(blank=True, null=True)
    process_date_pup = models.DateField(blank=True, null=True)
    account_no = models.CharField(max_length=20, blank=True, null=True)
    currency_code = models.CharField(max_length=3, blank=True, null=True)
    claim_amount = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    vesting_age = models.IntegerField(blank=True, null=True)
    bonus_year = models.IntegerField(blank=True, null=True)
    year_interim_bonus = models.IntegerField(blank=True, null=True)
    joint_age = models.IntegerField(blank=True, null=True)
    proportionate_sa = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    child_age = models.IntegerField(blank=True, null=True)
    emr = models.IntegerField(blank=True, null=True)
    net_paidup_value = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    duration = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mdf_print_request = models.CharField(max_length=1, blank=True, null=True)
    yrs_after_bonus = models.IntegerField(blank=True, null=True)
    policy_type = models.CharField(max_length=1, blank=True, null=True)
    cic = models.CharField(max_length=1, blank=True, null=True)
    cic_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cic_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cic_sum_assured = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cic_total_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    cic_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    dab = models.CharField(max_length=1, blank=True, null=True)
    ltb_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ltb_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb = models.CharField(max_length=1, blank=True, null=True)
    isb_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    partners_age = models.IntegerField(blank=True, null=True)
    female_smoker = models.CharField(max_length=1, blank=True, null=True)
    male_smoker = models.CharField(max_length=1, blank=True, null=True)
    joint_smoker = models.CharField(max_length=1, blank=True, null=True)
    type = models.CharField(max_length=1, blank=True, null=True)
    wp_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    wp_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    unexpired_period = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ltb = models.CharField(max_length=1, blank=True, null=True)
    access_age = models.IntegerField(blank=True, null=True)
    rate_type = models.CharField(max_length=1, blank=True, null=True)
    cic_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    isb_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    ltb_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    dab_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    wp_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    refund_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dab_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dab_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    maturity_age = models.IntegerField(blank=True, null=True)
    pol_fund = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    self_proposer = models.CharField(max_length=1, blank=True, null=True)
    deceased = models.CharField(max_length=1, blank=True, null=True)
    hse_loan_no = models.IntegerField(blank=True, null=True)
    takeon_due_date = models.DateField(blank=True, null=True)
    takeon_prems = models.IntegerField(blank=True, null=True)
    takeon_recvd = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    partners_no = models.CharField(max_length=8, blank=True, null=True)
    death_notified = models.CharField(max_length=1, blank=True, null=True)
    death_paid = models.CharField(max_length=1, blank=True, null=True)
    surrender_notified = models.CharField(max_length=1, blank=True, null=True)
    surrender_paid = models.CharField(max_length=1, blank=True, null=True)
    inst_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    leb = models.CharField(max_length=1, blank=True, null=True)
    leb_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    leb_extra_prem = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pol_type = models.CharField(max_length=1, blank=True, null=True)
    user_id = models.CharField(max_length=4, blank=True, null=True)
    offcd = models.CharField(max_length=3, blank=True, null=True)
    aload = models.IntegerField(blank=True, null=True)
    sa_discount = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    occup = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    reins_renewal_date = models.DateField(blank=True, null=True)
    reinsure_date = models.DateField(blank=True, null=True)
    reassure = models.CharField(max_length=1, blank=True, null=True)
    from_group = models.CharField(max_length=1, blank=True, null=True)
    scheme_no = models.CharField(max_length=9, blank=True, null=True)
    scheme_client = models.CharField(max_length=8, blank=True, null=True)
    bal_available = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    prev_loan = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    takeon_interest = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    accrued_interest = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    claim_reice = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    premium_due_date = models.DateField(blank=True, null=True)
    beneficiaries = models.CharField(max_length=24, blank=True, null=True)
    sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    partial_maturity = models.CharField(max_length=1, blank=True, null=True)
    guardian = models.CharField(max_length=24, blank=True, null=True)
    pers_bonus_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    fin_reference_no = models.CharField(max_length=15, blank=True, null=True)
    settlement_status = models.CharField(max_length=1, blank=True, null=True)
    late_fees = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ppa = models.CharField(max_length=1, blank=True, null=True)
    ppa_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ppa_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    fib = models.CharField(max_length=1, blank=True, null=True)
    fib_term = models.IntegerField(blank=True, null=True)
    fib_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    fib_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    unpaid_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    uppaid_premint = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    claim_settled = models.CharField(max_length=1, blank=True, null=True)
    debit_note_no = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    deposit = models.CharField(max_length=1, blank=True, null=True)
    rider_code = models.CharField(max_length=2, blank=True, null=True)
    life_units = models.IntegerField(blank=True, null=True)
    unit_linked = models.CharField(max_length=1, blank=True, null=True)
    ulf_code = models.CharField(max_length=3, blank=True, null=True)
    ul_units = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    ul_life_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ul_inv_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ul_type = models.IntegerField(blank=True, null=True)
    lien_option = models.CharField(max_length=1, blank=True, null=True)
    terminal_illness = models.CharField(max_length=1, blank=True, null=True)
    total_units = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    last_premium_date = models.DateField(blank=True, null=True)
    redeemed_units = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    ul_inv_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    update_1 = models.CharField(max_length=1, blank=True, null=True)
    update_2 = models.CharField(max_length=1, blank=True, null=True)
    update_3 = models.CharField(max_length=1, blank=True, null=True)
    new_agent = models.CharField(max_length=1, blank=True, null=True)
    orig_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    orig_prem_yr1 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    orig_prem_yr2 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    orig_prem_yr3 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    new_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    update_prems = models.CharField(max_length=1, blank=True, null=True)
    nof_redemptions = models.IntegerField(blank=True, null=True)
    redem_flag = models.CharField(max_length=1, blank=True, null=True)
    prev_redemption = models.IntegerField(blank=True, null=True)
    prev_units = models.DecimalField(max_digits=13, decimal_places=4, blank=True, null=True)
    identified_str = models.CharField(max_length=1, blank=True, null=True)
    stop_order_date = models.DateField(blank=True, null=True)
    rider = models.CharField(max_length=1, blank=True, null=True)
    redated = models.CharField(max_length=1, blank=True, null=True)
    bonus_value = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    prem_escalator = models.CharField(max_length=1, blank=True, null=True)
    escalator_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    cession_no = models.IntegerField(blank=True, null=True)
    mr_no = models.CharField(max_length=10, blank=True, null=True)
    period_year = models.IntegerField(blank=True, null=True)
    period_month = models.IntegerField(blank=True, null=True)
    loan_no = models.CharField(max_length=8, blank=True, null=True)
    pension_int_rate = models.DecimalField(max_digits=13, decimal_places=9, blank=True, null=True)
    value_acquired = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    age_f = models.IntegerField(blank=True, null=True)
    joint_age_f = models.IntegerField(blank=True, null=True)
    staff_yn = models.CharField(max_length=1, blank=True, null=True)
    pdoc_signed_yn = models.CharField(max_length=1, blank=True, null=True)
    pdoc_sign_date = models.DateField(blank=True, null=True)
    pdoc_printed_yn = models.CharField(max_length=1, blank=True, null=True)
    pdoc_print_date = models.DateField(blank=True, null=True)
    employee_no = models.CharField(max_length=15, blank=True, null=True)
    maturity_value_acquired = models.BigIntegerField(blank=True, null=True)
    death_guarantee_yn = models.CharField(max_length=1, blank=True, null=True)
    death_guarantee_prd = models.IntegerField(blank=True, null=True)
    employer_code = models.CharField(max_length=5, blank=True, null=True)
    installment_freq = models.IntegerField(blank=True, null=True)
    maturity_install_amt = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    edu_int_lumpsum_per = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    age_factor = models.IntegerField(blank=True, null=True)
    admin_charge = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    load_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    death_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    net_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    prem_after_comm = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    old_policy_type = models.CharField(max_length=1, blank=True, null=True)
    old_policy_serial = models.IntegerField(blank=True, null=True)
    old_policy_flag = models.CharField(max_length=1, blank=True, null=True)
    value_acquired_3yrs = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    policy_on = models.CharField(max_length=1, blank=True, null=True)
    interest_type = models.CharField(max_length=1, blank=True, null=True)
    sponsor = models.CharField(max_length=38, blank=True, null=True)
    esc_freq = models.IntegerField(blank=True, null=True)
    sponsor_no = models.CharField(max_length=8, blank=True, null=True)
    sponsor_type = models.CharField(max_length=1, blank=True, null=True)
    guarantee_death_prd = models.IntegerField(blank=True, null=True)
    cancel_user = models.CharField(max_length=12, blank=True, null=True)
    cancel_reason = models.CharField(max_length=30, blank=True, null=True)
    freq_install = models.CharField(max_length=1, blank=True, null=True)
    endorse_type = models.CharField(max_length=3, blank=True, null=True)
    prev_endorse_type = models.CharField(max_length=3, blank=True, null=True)
    endorse_year = models.IntegerField(blank=True, null=True)
    endorse_serial = models.IntegerField(blank=True, null=True)
    end_mat_install_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    end_pay_period = models.IntegerField(blank=True, null=True)
    end_installment_freq = models.IntegerField(blank=True, null=True)
    end_lumpsum_per = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    end_pay_mode = models.CharField(max_length=1, blank=True, null=True)
    end_basic_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    endorse_date = models.DateField(blank=True, null=True)
    max_premiums = models.IntegerField(blank=True, null=True)
    excess_units = models.IntegerField(blank=True, null=True)
    bene_type = models.IntegerField(blank=True, null=True)
    anniv_prem_units = models.IntegerField(blank=True, null=True)
    comm_flag = models.CharField(max_length=1, blank=True, null=True)
    pol_count = models.IntegerField(blank=True, null=True)
    show_vacq_yn = models.CharField(max_length=1, blank=True, null=True)
    maturity_install_amt1 = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    free_contribution = models.CharField(max_length=1, blank=True, null=True)
    pdoc_collected_by = models.CharField(max_length=50, blank=True, null=True)
    withdrawal_value_acquired = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    special_value_acquired = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    premium_value_acquired = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    members = models.IntegerField(blank=True, null=True)
    risk_sum_main = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    members_sum_assured = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    corporate_code = models.CharField(max_length=7)
    manager_code = models.IntegerField(blank=True, null=True)
    ptd_perc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ivalue = models.DecimalField(max_digits=20, decimal_places=9, blank=True, null=True)
    ptd_claim_yn = models.CharField(max_length=1, blank=True, null=True)
    ovp_no = models.IntegerField(blank=True, null=True)
    item_no = models.IntegerField(blank=True, null=True)
    install_fund_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    install_fund_uncollected = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    install_fund_total = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    pen_admin_charge = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    edu_admin_charge = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    int_rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    new_tarrif = models.CharField(max_length=1, blank=True, null=True)
    group_tarrif = models.CharField(max_length=7, blank=True, null=True)
    return_confirmed_by = models.CharField(max_length=8, blank=True, null=True)
    batch_reference = models.CharField(max_length=10, blank=True, null=True)
    cumm_min_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    sub_group = models.CharField(max_length=3, blank=True, null=True)
    converted_by = models.CharField(max_length=15, blank=True, null=True)
    paid_retained_comm = models.CharField(max_length=1, blank=True, null=True)
    salary_code = models.CharField(max_length=9, blank=True, null=True)
    convertion_month = models.IntegerField(blank=True, null=True)
    convertion_year = models.IntegerField(blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    auto_convert_flag = models.CharField(max_length=1, blank=True, null=True)
    user_name = models.CharField(max_length=20, blank=True, null=True)
    saham_policy_no = models.CharField(max_length=20, blank=True, null=True)
    saham_flag = models.CharField(max_length=1, blank=True, null=True)
    non_insurance_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    acquisition_cost = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    premium_review_date = models.DateField(blank=True, null=True)
    co_insure = models.CharField(max_length=1, blank=True, null=True)
    company_share = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    type_of_bus = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lapol'


class Lapro(models.Model):
    proposal_no = models.CharField(max_length=9,primary_key=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    unit_no = models.IntegerField(blank=True, null=True)
    branch = models.IntegerField(blank=True, null=True)
    type = models.IntegerField(blank=True, null=True)
    agent = models.IntegerField(blank=True, null=True)
    proposal_date = models.DateField(blank=True, null=True)
    plan = models.CharField(max_length=2, blank=True, null=True)
    pay_mode = models.CharField(max_length=1, blank=True, null=True)
    pay_method = models.CharField(max_length=1, blank=True, null=True)
    min_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ltb_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    status_code = models.CharField(max_length=2, blank=True, null=True)
    adb_sum = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    pre_issued = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    lastdep_date = models.DateField(blank=True, null=True)
    payment_suspense = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    refunded_amount = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    depdue_date = models.DateField(blank=True, null=True)
    sup_code = models.CharField(max_length=3, blank=True, null=True)
    deposit_due = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    prev_status = models.CharField(max_length=2, blank=True, null=True)
    cancel_date = models.DateField(blank=True, null=True)
    jointlife = models.CharField(max_length=1, blank=True, null=True)
    status_date = models.DateField(blank=True, null=True)
    user_id = models.CharField(max_length=4, blank=True, null=True)
    received = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    creation_date = models.DateField(blank=True, null=True)
    creation_id = models.CharField(max_length=4, blank=True, null=True)
    medical_results = models.CharField(max_length=1, blank=True, null=True)
    mode_extra = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    previous_payment_date = models.DateField(blank=True, null=True)
    void_date = models.DateField(blank=True, null=True)
    term_of_policy = models.IntegerField(blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    conversion_date = models.DateField(blank=True, null=True)
    bank_no = models.CharField(max_length=6, blank=True, null=True)
    account_no = models.CharField(max_length=15, blank=True, null=True)
    cheque_no = models.CharField(max_length=15, blank=True, null=True)
    pol_fund = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    refund_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    penalty_todate = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    fin_reference_no = models.CharField(max_length=15, blank=True, null=True)
    med_fees_paid = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    doct_pay_date = models.DateField(blank=True, null=True)
    previous_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    receipt_no = models.CharField(max_length=10, blank=True, null=True)
    doctor_code = models.CharField(max_length=4, blank=True, null=True)
    modal_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    debit_issue_date = models.DateField(blank=True, null=True)
    debit_note_no = models.IntegerField(blank=True, null=True)
    cic = models.CharField(max_length=1, blank=True, null=True)
    cic_female_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    cic_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cic_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    cic_joint = models.CharField(max_length=1, blank=True, null=True)
    ltb = models.CharField(max_length=1, blank=True, null=True)
    ltb_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ltb_female_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ltb_term = models.IntegerField(blank=True, null=True)
    dab = models.CharField(max_length=1, blank=True, null=True)
    dab_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dab_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    wp = models.CharField(max_length=1, blank=True, null=True)
    wp_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    wp_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb = models.CharField(max_length=1, blank=True, null=True)
    isb_female_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb_male_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb_sum_assured = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    male_smoker = models.CharField(max_length=1, blank=True, null=True)
    female_smoker = models.CharField(max_length=1, blank=True, null=True)
    joint_smoker = models.CharField(max_length=1, blank=True, null=True)
    access_age = models.IntegerField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    joint_age = models.IntegerField(blank=True, null=True)
    rate_type = models.CharField(max_length=1, blank=True, null=True)
    cic_total_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    basic_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    wp_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dab_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    isb_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cic_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    ltb_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    isb_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    dab_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    wp_2nd_life = models.CharField(max_length=1, blank=True, null=True)
    partners_age = models.IntegerField(blank=True, null=True)
    ltb_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    pay_period = models.IntegerField(blank=True, null=True)
    mortgage_protection = models.CharField(max_length=1, blank=True, null=True)
    partners_dob = models.DateField(blank=True, null=True)
    partners_no = models.CharField(max_length=8, blank=True, null=True)
    leb = models.CharField(max_length=1, blank=True, null=True)
    leb_premium = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    nonsmoking_disc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    maturity_age = models.IntegerField(blank=True, null=True)
    vesting_age = models.IntegerField(blank=True, null=True)
    leb_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    dab_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    currency_code = models.CharField(max_length=3, blank=True, null=True)
    aload = models.IntegerField(blank=True, null=True)
    emr = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    sa_discount = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    occup = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    offcd = models.CharField(max_length=3, blank=True, null=True)
    quoted = models.CharField(max_length=1, blank=True, null=True)
    quotation_no = models.IntegerField(blank=True, null=True)
    extra_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    scheme_no = models.CharField(max_length=9, blank=True, null=True)
    scheme_client = models.CharField(max_length=8, blank=True, null=True)
    from_group = models.CharField(max_length=1, blank=True, null=True)
    med_exemption = models.CharField(max_length=1, blank=True, null=True)
    beneficiary_created = models.CharField(max_length=1, blank=True, null=True)
    setup_year = models.BooleanField(blank=True, null=True)
    guardian = models.CharField(max_length=24, blank=True, null=True)
    ppa = models.CharField(max_length=1, blank=True, null=True)
    ppa_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ppa_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    fib = models.CharField(max_length=1, blank=True, null=True)
    fib_term = models.IntegerField(blank=True, null=True)
    fib_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    fib_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    med_required = models.CharField(max_length=1, blank=True, null=True)
    partners_names = models.CharField(max_length=20, blank=True, null=True)
    partners_sex = models.CharField(max_length=1, blank=True, null=True)
    rider_code = models.CharField(max_length=2, blank=True, null=True)
    rider_term = models.IntegerField(blank=True, null=True)
    rider_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rider_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rider = models.CharField(max_length=1, blank=True, null=True)
    deposit = models.CharField(max_length=1, blank=True, null=True)
    prop_on = models.CharField(max_length=1, blank=True, null=True)
    unit_linked = models.CharField(max_length=1, blank=True, null=True)
    ulf_code = models.CharField(max_length=3, blank=True, null=True)
    ul_inv_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ul_life_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ul_type = models.IntegerField(blank=True, null=True)
    life_units = models.IntegerField(blank=True, null=True)
    medicals = models.CharField(max_length=1, blank=True, null=True)
    lien_option = models.CharField(max_length=1, blank=True, null=True)
    terminal_illness = models.CharField(max_length=1, blank=True, null=True)
    premium_escalator = models.CharField(max_length=1, blank=True, null=True)
    escalator_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    med_fees_due = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    date_prop_recvd = models.DateField(blank=True, null=True)
    pension_int_rate = models.DecimalField(max_digits=13, decimal_places=9, blank=True, null=True)
    value_acquired = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    age_f = models.IntegerField(blank=True, null=True)
    joint_age_f = models.IntegerField(blank=True, null=True)
    interest_type = models.CharField(max_length=1, blank=True, null=True)
    staff_yn = models.CharField(max_length=1, blank=True, null=True)
    medreq_printed_yn = models.CharField(max_length=1, blank=True, null=True)
    medreq_printed_by = models.CharField(max_length=8, blank=True, null=True)
    medreq_printed_on = models.DateField(blank=True, null=True)
    employee_no = models.CharField(max_length=15, blank=True, null=True)
    age_factor = models.IntegerField(blank=True, null=True)
    death_guarantee_yn = models.CharField(max_length=1, blank=True, null=True)
    death_guarantee_prd = models.IntegerField(blank=True, null=True)
    prem_after_comm = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    maturity_install_amt = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    edu_int_lumpsum_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    employer_code = models.CharField(max_length=5, blank=True, null=True)
    esc_freq = models.BooleanField(blank=True, null=True)
    user_no = models.IntegerField(blank=True, null=True)
    value_acquired_3yrs = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    maturity_value_acquired = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    sponsor_no = models.CharField(max_length=8, blank=True, null=True)
    guarantee_death_prd = models.IntegerField(blank=True, null=True)
    freq_install = models.CharField(max_length=1, blank=True, null=True)
    admin_charge = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    load_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    death_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    comm_flag = models.CharField(max_length=1, blank=True, null=True)
    user_str = models.CharField(max_length=14, blank=True, null=True)
    free_contribution = models.CharField(max_length=1, blank=True, null=True)
    sponsor_type = models.CharField(max_length=1, blank=True, null=True)
    max_free_cover = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    members = models.IntegerField(blank=True, null=True)
    risk_sum_main = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    members_sum_assured = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    corporate_code = models.CharField(max_length=7)
    supervisor_no = models.IntegerField(blank=True, null=True)
    manager_code = models.IntegerField(blank=True, null=True)
    ivalue = models.DecimalField(max_digits=20, decimal_places=9, blank=True, null=True)
    ovp_no = models.IntegerField(blank=True, null=True)
    item_no = models.IntegerField(blank=True, null=True)
    pen_admin_charge = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    edu_admin_charge = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    int_rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    new_tarrif = models.CharField(max_length=1, blank=True, null=True)
    group_tarrif = models.CharField(max_length=7, blank=True, null=True)
    product_code = models.IntegerField(blank=True, null=True)
    plan_code = models.CharField(max_length=5, blank=True, null=True)
    modified_by = models.CharField(max_length=10, blank=True, null=True)
    modified_date = models.DateField(blank=True, null=True)
    fab = models.CharField(max_length=1, blank=True, null=True)
    fab_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    fab_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ppd = models.CharField(max_length=1, blank=True, null=True)
    ppd_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ppd_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    rev = models.CharField(max_length=1, blank=True, null=True)
    rev_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    rev_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    crt = models.CharField(max_length=1, blank=True, null=True)
    crt_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    crt_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    tpd = models.CharField(max_length=1, blank=True, null=True)
    tpd_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    tpd_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    sub_group = models.CharField(max_length=3, blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    salary_code = models.CharField(max_length=9, blank=True, null=True)
    p_policy_no = models.CharField(max_length=9, blank=True, null=True)
    user_name = models.CharField(max_length=20, blank=True, null=True)
    saham_flag = models.CharField(max_length=1, blank=True, null=True)
    saham_client_no = models.IntegerField(blank=True, null=True)
    saham_agent_no = models.CharField(max_length=5, blank=True, null=True)
    saham_proposal_no = models.CharField(max_length=20, blank=True, null=True)
    non_insurance_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    acquisition_cost = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    premium_review_date = models.DateField(blank=True, null=True)
    co_insure = models.CharField(max_length=1, blank=True, null=True)
    company_share = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    type_of_bus = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lapro'

class Bankstatedtl(models.Model):
    ref_no = models.CharField(max_length=19, blank=True, null=True)
    corporate_code = models.CharField(max_length=7, blank=True, null=True)
    source_code = models.CharField(max_length=3, blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    trans_amount = models.DecimalField(max_digits=20, decimal_places=2)
    dola = models.DateField(blank=True, null=True)
    trans_date = models.DateField(blank=True, null=True)
    date_posted = models.DateField(blank=True, null=True)
    user_str = models.CharField(max_length=15, blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    client_name = models.CharField(max_length=100, blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    proposal_no = models.CharField(max_length=9, blank=True, null=True)
    receipt_for = models.CharField(max_length=1, blank=True, null=True)
    changed_by = models.CharField(max_length=15, blank=True, null=True)
    item_no = models.IntegerField(blank=True, null=True)
    group_tariff = models.CharField(max_length=7, blank=True, null=True)
    ovp_group = models.CharField(max_length=1, blank=True, null=True)
    member_no = models.IntegerField(blank=True, null=True)
    payroll_no = models.CharField(max_length=10, blank=True, null=True)
    chk_no = models.IntegerField(blank=True, null=True)
    grp_item_no = models.IntegerField(blank=True, null=True)
    status_code = models.CharField(max_length=1, blank=True, null=True)
    policy_status = models.CharField(max_length=2, blank=True, null=True)
    plan = models.CharField(max_length=2, blank=True, null=True)
    pension_ee_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    pension_er_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    pension_ee_single_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    pension_er_single_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)
    receipt_no = models.CharField(max_length=10, blank=True, null=True)
    narration = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'bankstatedtl'


class Corpmonthschedgrp(models.Model):
    item_no = models.IntegerField(blank=True, null=True)
    ref_no = models.CharField(max_length=19, blank=True, null=True)
    source_code = models.CharField(max_length=3, blank=True, null=True)
    trans_date = models.DateField(blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    group_tariff = models.CharField(max_length=7, blank=True, null=True)
    trans_amount = models.DecimalField(max_digits=20, decimal_places=2)
    date_posted = models.DateField(blank=True, null=True)
    user_str = models.CharField(max_length=15, blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    chk_no = models.IntegerField(blank=True, null=True)
    status_code = models.CharField(max_length=1, blank=True, null=True)
    group_name = models.CharField(max_length=100, blank=True, null=True)
    receipt_no = models.CharField(max_length=10, blank=True, null=True)
    link_code = models.IntegerField(blank=True, null=True)
    linked_flag = models.CharField(max_length=1, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'corpmonthschedgrp'


class Corpmonthsusp(models.Model):
    ref_no = models.CharField(max_length=19, blank=True, null=True)
    receipt_no = models.CharField(max_length=10, blank=True, null=True)
    trans_type = models.CharField(max_length=3)
    ref_ref_no = models.CharField(max_length=19, blank=True, null=True)
    ref_item_no = models.IntegerField(blank=True, null=True)
    status_code = models.CharField(max_length=1, blank=True, null=True)
    effective_date = models.DateField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    item_no = models.IntegerField(blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    source_code = models.CharField(max_length=3, blank=True, null=True)
    group_tariff = models.CharField(max_length=7, blank=True, null=True)
    client_name = models.CharField(max_length=100, blank=True, null=True)
    user_str = models.CharField(max_length=15, blank=True, null=True)
    suspense_receipt_no = models.CharField(max_length=10, blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    old_suspense_flag = models.CharField(max_length=1, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'corpmonthsusp'