from django.db import models
from django.utils import timezone

# Create your models here.


class Fleetusers(models.Model):
    user_name = models.CharField(primary_key=True,max_length=15)
    upload_fleet = models.CharField(max_length=1, blank=True, null=True)
    review_fleet = models.CharField(max_length=1, blank=True, null=True)
    process_fleet = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        db_table = 'fleetusers'


class BatchSerial(models.Model):
    serial_no = models.IntegerField()

    def __str__(self):
        return str(self.serial_no)


class BatchCode(models.Model):
    batch_no = models.CharField(max_length=8,primary_key=True)
    created_date = models.DateField(default=timezone.now)
    processed = models.CharField(max_length=1,default='N')
    process_date = models.DateField(blank=True,null=True)
    processed_by = models.CharField(max_length=15, blank=True, null=True, default='')
    policy_no = models.CharField(max_length=19,blank=True)
    created_by = models.CharField(max_length=15,blank=True,null=True,default='')
    reviewed_by = models.CharField(max_length=15,blank=True,null=True,default='')
    reveiwed = models.CharField(max_length=1,default='N')
    reveiwed_date = models.DateField(blank=True, null=True )
    premium_total = models.DecimalField(decimal_places=2,default=0,max_digits=20)
    sum_total = models.DecimalField(decimal_places=2,default=0,max_digits=20)
    uploaded_by = models.CharField(max_length=15,blank=True,null=True,default='')
    batch_type = models.IntegerField(blank=True,null=True)
    #binder = models.CharField(max_length=1,default='N')
    #binder_pol_no = models.CharField(max_length=19,blank=True,null=True)

    class Meta:
        ordering = ['-batch_no']
        verbose_name_plural = 'BatchCode'
        verbose_name='BatchCode'

    def __str__(self):
        return self.batch_no


class Schememaster(models.Model):
    policy_no = models.CharField(max_length=9,primary_key=True)
    uw_year = models.IntegerField(blank=True, null=True)
    scheme_type = models.CharField(max_length=3, blank=True, null=True)
    client_no = models.CharField(max_length=8)
    branch = models.IntegerField()
    agent = models.IntegerField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    renewal_date = models.DateField(blank=True, null=True)
    period_from = models.DateField(blank=True, null=True)
    period_to = models.DateField(blank=True, null=True)
    pay_freq = models.CharField(max_length=1, blank=True, null=True)
    pay_mode = models.CharField(max_length=1, blank=True, null=True)
    annual_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    user_str = models.CharField(max_length=15, blank=True, null=True)
    total_members = models.IntegerField(blank=True, null=True)
    sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loans_count = models.IntegerField(blank=True, null=True)
    status_code = models.IntegerField(blank=True, null=True)
    deactivation_date = models.DateField(blank=True, null=True)
    deactivated_by = models.CharField(max_length=15, blank=True, null=True)
    last_edited_by = models.CharField(max_length=15, blank=True, null=True)
    retirement_age = models.IntegerField(blank=True, null=True)
    minimum_contribution = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    maximum_contribution = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    employer_contrib = models.DecimalField(max_digits=8, decimal_places=4, blank=True, null=True)
    employee_contrib = models.DecimalField(max_digits=8, decimal_places=4, blank=True, null=True)
    aims_ledger = models.CharField(max_length=10, blank=True, null=True)
    sage_ledger = models.CharField(max_length=10, blank=True, null=True)
    sage_sub_ledger = models.CharField(max_length=10, blank=True, null=True)
    tin_no = models.CharField(max_length=15, blank=True, null=True)
    tin_reg_date = models.DateField(blank=True, null=True)
    scheme_name = models.CharField(max_length=100, blank=True, null=True)
    interest_rate = models.DecimalField(max_digits=8, decimal_places=4, blank=True, null=True)
    admin_fee = models.DecimalField(max_digits=8, decimal_places=4, blank=True, null=True)
    date_created = models.DateField(blank=True, null=True)
    source_code = models.CharField(max_length=3, blank=True, null=True)
    commission_rate = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    tl_code = models.CharField(max_length=5, blank=True, null=True)
    lc_factor = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    load_flag = models.CharField(max_length=1, blank=True, null=True)
    mod_factor = models.DecimalField(max_digits=15, decimal_places=6, blank=True, null=True)
    mp_insurance = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    units_rates_app = models.CharField(max_length=1, blank=True, null=True)
    unit_rate = models.DecimalField(max_digits=13, decimal_places=6, blank=True, null=True)
    bank_code = models.IntegerField(blank=True, null=True)
    categ_ind = models.CharField(max_length=1, blank=True, null=True)
    br_ind = models.CharField(max_length=1, blank=True, null=True)
    with_rider = models.CharField(max_length=1, blank=True, null=True)
    savings_yn = models.CharField(max_length=1, blank=True, null=True)
    min_sa_ind = models.CharField(max_length=1, blank=True, null=True)
    max_sa_ind = models.CharField(max_length=1, blank=True, null=True)
    min_sum_assured = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    max_sum_assured = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    without_salary_ind = models.CharField(max_length=1, blank=True, null=True)
    without_salary_sa = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    with_discount = models.CharField(max_length=1, blank=True, null=True)
    discount_per = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    free_cover_limit = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    j_unit_rate = models.DecimalField(max_digits=13, decimal_places=6, blank=True, null=True)
    admin_included = models.CharField(max_length=1, blank=True, null=True)
    admin_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    ass_int_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    comm_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    total_sum_assured = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    total_annual_salary = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    gross_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    nett_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    total_loans = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_of_rev_yn = models.CharField(max_length=1, blank=True, null=True)
    loss_of_rev_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    ppd_yn = models.CharField(max_length=1, blank=True, null=True)
    ppd_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loading_factor_ind = models.CharField(max_length=1, blank=True, null=True)
    loading_factor_per = models.IntegerField(blank=True, null=True)
    ren_type = models.CharField(max_length=1, blank=True, null=True)
    esc_freq = models.IntegerField(blank=True, null=True)
    esc_factor = models.IntegerField(blank=True, null=True)
    total_rider_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    renewal_mode = models.CharField(max_length=1, blank=True, null=True)
    expired_date = models.DateField(blank=True, null=True)
    under_renewal = models.CharField(max_length=1, blank=True, null=True)
    joint_rate_flag = models.CharField(max_length=1, blank=True, null=True)
    paid_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    ytd_balance = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    commission_pay_period = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    premium_due_date = models.DateField(blank=True, null=True)
    new_sage_ledger = models.CharField(max_length=15, blank=True, null=True)
    renewalable_flag = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'schememaster'



class Membermaster(models.Model):
    policy_no = models.CharField(max_length=9)
    member_no = models.IntegerField(primary_key=True)
    client_no = models.CharField(max_length=8)
    payroll_no = models.CharField(max_length=10, blank=True, null=True)
    join_date = models.DateField(blank=True, null=True)
    employment_date = models.DateField(blank=True, null=True)
    date_left = models.DateField(blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    surname = models.CharField(max_length=50, blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    other_names = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    tin_no = models.CharField(max_length=15, blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)
    status_code = models.IntegerField(blank=True, null=True)
    pay_freq = models.CharField(max_length=1, blank=True, null=True)
    annual_salary = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    id_type = models.CharField(max_length=2, blank=True, null=True)
    id_no = models.CharField(max_length=15, blank=True, null=True)
    employer_contrib = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    employee_contrib = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    employer_contrib_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    employee_contrib_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    maturity_date = models.DateField(blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    user_str = models.CharField(max_length=15, blank=True, null=True)
    created_by = models.CharField(max_length=15, blank=True, null=True)
    date_created = models.DateField(blank=True, null=True)
    deactivated_by = models.CharField(max_length=15, blank=True, null=True)
    deactivation_date = models.DateField(blank=True, null=True)
    branch = models.IntegerField(blank=True, null=True)
    agent = models.IntegerField(blank=True, null=True)
    retirement_age = models.IntegerField(blank=True, null=True)
    institute_client_number = models.CharField(max_length=8, blank=True, null=True)
    lc_cover_factor = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    base = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    current_salary = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    app_form_id = models.CharField(max_length=1, blank=True, null=True)
    emp_dec_ind = models.CharField(max_length=1, blank=True, null=True)
    restricted_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rider_benefit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rider_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_norm_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    savings_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    savings_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_total_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    medical_req = models.CharField(max_length=1, blank=True, null=True)
    sum_assured_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    new_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    annual_prem_rate = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_new_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ppd_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_of_rev_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    comm_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    scheme_type = models.CharField(max_length=3, blank=True, null=True)
    renewal_date = models.DateField(blank=True, null=True)
    medical_uw_loading = models.IntegerField(blank=True, null=True)
    marital_status = models.CharField(max_length=1, blank=True, null=True)
    pay_mode = models.CharField(max_length=6, blank=True, null=True)
    branch_no = models.CharField(max_length=2, blank=True, null=True)
    uw_decision = models.IntegerField(blank=True, null=True)
    est_loan_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    acceptance_terms_issued = models.CharField(max_length=1, blank=True, null=True)
    uw_ind = models.CharField(max_length=1, blank=True, null=True)
    loans_granted = models.IntegerField(blank=True, null=True)
    uw_date = models.DateField(blank=True, null=True)
    lc_extra_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    orig_sum_insured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    canc_reason = models.CharField(max_length=20, blank=True, null=True)
    top_member_no = models.IntegerField(blank=True, null=True)
    sn_no1 = models.CharField(max_length=11, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)
    modified_date = models.DateField(blank=True, null=True)
    modified_by = models.CharField(max_length=15, blank=True, null=True)
    sn_no = models.IntegerField(blank=True, null=True)
    term_of_savings = models.IntegerField(blank=True, null=True)
    term_years = models.IntegerField(blank=True, null=True)
    pol_fund = models.BigIntegerField(blank=True, null=True)
    lc_supp_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    premium_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    renewal_mode = models.CharField(max_length=1, blank=True, null=True)
    confirm_ren = models.CharField(max_length=1, blank=True, null=True)
    period_from = models.DateField(blank=True, null=True)
    period_to = models.DateField(blank=True, null=True)
    received_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    balance = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    topup = models.CharField(max_length=1, blank=True, null=True)
    old_member_no = models.IntegerField(blank=True, null=True)
    fcrm = models.CharField(max_length=1, blank=True, null=True)
    premium_due_date = models.DateField(blank=True, null=True)
    premium_review_date = models.DateField(blank=True, null=True)
    acquisition_cost = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    non_insurance_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    type_of_bus = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    co_insure = models.CharField(max_length=1, blank=True, null=True)
    company_share = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    dept_no = models.IntegerField(blank=True, null=True)
    comm_rate = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)
    retrenchment = models.CharField(max_length=1, blank=True, null=True)
    retrench_period = models.IntegerField(blank=True, null=True)
    crm_flag = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False

        indexes = [models.Index(fields=['policy_no', ]),
                   models.Index(fields=['member_no', ])]

        db_table = 'membermaster'


class Glclmast(models.Model):
    client_no = models.CharField(max_length=8, primary_key=True)
    title = models.CharField(max_length=4, blank=True, null=True)
    surname = models.CharField(max_length=40, blank=True, null=True)
    other_names = models.CharField(max_length=30, blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    address = models.CharField(max_length=20, blank=True, null=True)
    location = models.CharField(max_length=20, blank=True, null=True)
    town = models.CharField(max_length=20, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    marital_status = models.CharField(max_length=1, blank=True, null=True)
    occupation_code = models.CharField(max_length=4, blank=True, null=True)
    employer_code = models.CharField(max_length=5, blank=True, null=True)
    birth_place = models.CharField(max_length=24, blank=True, null=True)
    identity_card_no = models.CharField(max_length=16, blank=True, null=True)
    employee_no = models.CharField(max_length=15, blank=True, null=True)
    user_id = models.CharField(max_length=4, blank=True, null=True)
    creation_date = models.DateField(blank=True, null=True)
    creation_id = models.CharField(max_length=4, blank=True, null=True)
    pin_number = models.CharField(max_length=15, blank=True, null=True)
    identity_type = models.CharField(max_length=2, blank=True, null=True)
    name = models.CharField(max_length=40, blank=True, null=True)
    sort_no = models.IntegerField(blank=True, null=True)
    sort_type = models.CharField(max_length=1, blank=True, null=True)
    amount_received = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    cession_no = models.CharField(max_length=8, blank=True, null=True)
    group_str = models.CharField(max_length=2, blank=True, null=True)
    branch_code = models.IntegerField(blank=True, null=True)
    client_type = models.CharField(max_length=1, blank=True, null=True)
    bnk_cd = models.CharField(max_length=3, blank=True, null=True)
    bch_cd = models.CharField(max_length=3, blank=True, null=True)
    bank_account = models.CharField(max_length=12, blank=True, null=True)
    client_name = models.CharField(max_length=48, blank=True, null=True)
    occup_loading = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    user1 = models.CharField(max_length=60, blank=True, null=True)
    tel1 = models.BigIntegerField(blank=True, null=True)
    tel2 = models.BigIntegerField(blank=True, null=True)
    tel3 = models.BigIntegerField(blank=True, null=True)
    province_code = models.CharField(max_length=2, blank=True, null=True)
    district_code = models.CharField(max_length=2, blank=True, null=True)
    sector_code = models.CharField(max_length=2, blank=True, null=True)
    id_no_country = models.CharField(max_length=1, blank=True, null=True)
    id_no_serial = models.CharField(max_length=12, blank=True, null=True)
    id_no_status = models.CharField(max_length=1, blank=True, null=True)
    id_no_count = models.CharField(max_length=2, blank=True, null=True)
    new_id_no = models.CharField(max_length=16, blank=True, null=True)
    rdb_reg_no = models.IntegerField(blank=True, null=True)
    rdb_reg_date = models.DateField(blank=True, null=True)
    tin_no = models.IntegerField(blank=True, null=True)
    joint_member = models.CharField(max_length=1, blank=True, null=True)
    status_code = models.IntegerField(blank=True, null=True)
    old_client_no = models.CharField(max_length=8, blank=True, null=True)
    company_name = models.CharField(max_length=20, blank=True, null=True)
    bnr_classification = models.CharField(max_length=3, blank=True, null=True)
    resident_country = models.CharField(max_length=4, blank=True, null=True)
    id_doc = models.CharField(max_length=1, blank=True, null=True)
    country_code = models.CharField(max_length=4, blank=True, null=True)
    spourse_name = models.CharField(max_length=998, blank=True, null=True)
    birth_reg_village = models.CharField(max_length=98, blank=True, null=True)
    residence_type = models.CharField(max_length=1, blank=True, null=True)
    economic_sub_sector = models.CharField(max_length=98, blank=True, null=True)
    relation_to_company_code = models.CharField(max_length=98, blank=True, null=True)
    cellule = models.CharField(max_length=98, blank=True, null=True)
    village = models.CharField(max_length=98, blank=True, null=True)
    contact = models.CharField(max_length=45, blank=True, null=True)
    contact_position = models.CharField(max_length=20, blank=True, null=True)
    contact_telephone = models.CharField(max_length=25, blank=True, null=True)
    naics_code = models.CharField(max_length=58, blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    address2 = models.CharField(max_length=20, blank=True, null=True)
    address3 = models.CharField(max_length=20, blank=True, null=True)
    fax = models.CharField(max_length=15, blank=True, null=True)
    province = models.IntegerField(blank=True, null=True)
    district = models.CharField(max_length=98, blank=True, null=True)
    sector = models.CharField(max_length=98, blank=True, null=True)
    resident_country_1 = models.CharField(max_length=4, blank=True, null=True)
    country_code_1 = models.CharField(max_length=4, blank=True, null=True)
    cleaned_flag = models.CharField(max_length=1, blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    mobile_no = models.IntegerField(blank=True, null=True)
    occupation = models.CharField(max_length=30, blank=True, null=True)
    telephone = models.CharField(max_length=12, blank=True, null=True)
    id_unique = models.CharField(max_length=13, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)
    crm_flag_new = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glclmast'


class Memberupd(models.Model):
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    id_number = models.CharField(max_length=16, blank=True, null=True)
    fname = models.CharField(max_length=100, blank=True, null=True)
    lname = models.CharField(max_length=100, blank=True, null=True)
    surname = models.CharField(max_length=100, blank=True, null=True)
    full_name = models.CharField(max_length=200, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    birth_year = models.IntegerField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    monthly_sal = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    annual_sal = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    death_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    partial_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_income_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    dread_disease_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_staff_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_legal_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    medical_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    death_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    partial_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_of_income_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    dread_diseases_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_staff_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_legal_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    medical_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    total_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)
    #id = models.AutoField(primary_key=True)


    class Meta:
        managed = False
        db_table = 'Memberupd'

class MemberupdNew(models.Model):
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    id_number = models.CharField(max_length=30, blank=True, null=True)
    fname = models.CharField(max_length=100, blank=True, null=True)
    lname = models.CharField(max_length=100, blank=True, null=True)
    surname = models.CharField(max_length=100, blank=True, null=True)
    full_name = models.CharField(max_length=200, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    birth_year = models.IntegerField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    monthly_sal = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    annual_sal = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    death_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    partial_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_income_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    dread_disease_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_staff_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_legal_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    medical_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    death_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    partial_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_of_income_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    dread_diseases_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_staff_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_legal_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    medical_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    total_premium = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    batch_no = models.ForeignKey(BatchCode,on_delete=models.DO_NOTHING,blank=True,default='BA000001')
    join_date = models.DateField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    client_type=models.CharField(max_length=1,blank=True, null=True)
    fun_fees_dep_sum = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    fun_fees_dep_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    prorated_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)

    commence_date = models.DateField(blank=True, null=True)
    loan_period = models.IntegerField(blank=True, null=True)
    interest_basis = models.CharField(max_length=1,blank=True,null=True)
    interest_rate = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    loan_amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    admin_fee = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    vat = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    retrenchment = models.CharField(max_length=1, blank=True, null=True)
    branch = models.IntegerField(blank=True, null=True)
    id_type = models.IntegerField(blank=True, null=True)
    retrench_period = models.IntegerField(blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    processed_flag = models.CharField(max_length=1, blank=True, null=True)




    #id = models.AutoField(primary_key=True)

    class Meta:
        #managed = False
        db_table = 'MemberupdNew'


class Glriders(models.Model):
    code = models.IntegerField(blank=True, null=True)
    description = models.CharField(max_length=30, blank=True, null=True)
    filler = models.CharField(max_length=68, blank=True, null=True)
    gl_flag = models.CharField(max_length=1, blank=True, null=True)
    gc_flag = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glriders'






class Glmmridtl(models.Model):
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    member_no = models.IntegerField(blank=True, null=True)
    rider_code = models.IntegerField(blank=True, null=True)
    benefit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    plan = models.CharField(max_length=1, blank=True, null=True)
    mandatory_share = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    mandatory_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    mandatory_comm_amt = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    co_risk_retention = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    co_prem_retention = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    quota_share = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_share_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    quota_comm_amt = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_1 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_premium_2 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_premium_3 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_1 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_2 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_3 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    facult_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    facult_comm_amt = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    mandatory_share_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    co_reass_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    quota_share_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    surplus_rate_1 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    surplus_rate_2 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    surplus_rate_3 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    facult_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    principal_yn = models.BooleanField(blank=True, null=True)
    partners_no = models.CharField(max_length=8, blank=True, null=True)
    surname = models.CharField(max_length=15, blank=True, null=True)
    other_names = models.CharField(max_length=20, blank=True, null=True)
    commence_date = models.DateField(blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    age_treaty = models.IntegerField(blank=True, null=True)
    payroll_no = models.CharField(max_length=10, blank=True, null=True)
    ta_status = models.CharField(max_length=1, blank=True, null=True)
    filler = models.CharField(max_length=8, blank=True, null=True)
    loan_no = models.IntegerField(blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)
    retrenchment = models.CharField(max_length=1, blank=True, null=True)
    retrenchment_period = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glmmridtl'


class Glmploan(models.Model):
    client_no = models.CharField(max_length=8, blank=True, null=True)
    account_no = models.CharField(max_length=12, blank=True, null=True)
    loan_no = models.IntegerField(blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    member_no = models.IntegerField(blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    loan_status = models.BooleanField(blank=True, null=True)
    joint_loan = models.CharField(max_length=1, blank=True, null=True)
    commence_date = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    total_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    annual_prem_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    term_years = models.IntegerField(blank=True, null=True)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    lc_norm_annual_prem = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    redemtion_date = models.DateField(blank=True, null=True)
    year_of_death = models.IntegerField(blank=True, null=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    joint_age_1 = models.IntegerField(blank=True, null=True)
    joint_age_2 = models.IntegerField(blank=True, null=True)
    joint_age_3 = models.IntegerField(blank=True, null=True)
    joint_age_4 = models.IntegerField(blank=True, null=True)
    joint_age_5 = models.IntegerField(blank=True, null=True)
    prem_refund = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    comm_reclaim = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    co_prem_retention = models.BigIntegerField(blank=True, null=True)
    co_risk_retention = models.BigIntegerField(blank=True, null=True)
    co_reass_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    orig_sum_insured = models.BigIntegerField(blank=True, null=True)
    mandatory_share = models.BigIntegerField(blank=True, null=True)
    mandatory_comm_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mandatory_comm_amt = models.BigIntegerField(blank=True, null=True)
    mandatory_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    other_retention = models.BigIntegerField(blank=True, null=True)
    quota_share = models.BigIntegerField(blank=True, null=True)
    quota_comm_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    quota_comm_amt = models.BigIntegerField(blank=True, null=True)
    quota_share_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    quota_share_rate = models.IntegerField(blank=True, null=True)
    supplus_amount_1 = models.BigIntegerField(blank=True, null=True)
    supplus_amount_2 = models.BigIntegerField(blank=True, null=True)
    supplus_amount_3 = models.BigIntegerField(blank=True, null=True)
    surplus_premium_1 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_premium_2 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_premium_3 = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_rate_1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_rate_2 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_rate_3 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_comm_rate_1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_comm_rate_2 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_comm_rate_3 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    facult_amount = models.BigIntegerField(blank=True, null=True)
    facult_premium = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    facult_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    reass_prem_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    restricted_sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    medical_uw_loading = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    sum_assured_bf = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    quota_extra_prem = models.BigIntegerField(blank=True, null=True)
    surplus_extra_prem_1 = models.BigIntegerField(blank=True, null=True)
    surplus_extra_prem_2 = models.BigIntegerField(blank=True, null=True)
    surplus_extra_prem_3 = models.BigIntegerField(blank=True, null=True)
    facult_extra_prem = models.BigIntegerField(blank=True, null=True)
    mandatory_share_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mandatory_extra_prem = models.BigIntegerField(blank=True, null=True)
    facult_comm_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    facult_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    retention_extra_prem = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    surplus_amount_1 = models.BigIntegerField(blank=True, null=True)
    surplus_amount_2 = models.BigIntegerField(blank=True, null=True)
    surplus_amount_3 = models.BigIntegerField(blank=True, null=True)
    surplus_comm_amt_1 = models.BigIntegerField(blank=True, null=True)
    surplus_comm_amt_2 = models.BigIntegerField(blank=True, null=True)
    surplus_comm_amt_3 = models.BigIntegerField(blank=True, null=True)
    facult_comm_amt = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    claim_number = models.CharField(max_length=13, blank=True, null=True)
    term_months = models.IntegerField(blank=True, null=True)
    single_int_flag = models.CharField(max_length=1, blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    age_f = models.IntegerField(blank=True, null=True)
    joint_age_f_1 = models.IntegerField(blank=True, null=True)
    joint_age_f_2 = models.IntegerField(blank=True, null=True)
    joint_age_f_3 = models.IntegerField(blank=True, null=True)
    joint_age_f_4 = models.IntegerField(blank=True, null=True)
    joint_age_f_5 = models.IntegerField(blank=True, null=True)
    staff_yn = models.CharField(max_length=1, blank=True, null=True)
    admin_charge = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    prem_rate = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    comm_premium = models.IntegerField(blank=True, null=True)
    user1 = models.CharField(max_length=149, blank=True, null=True)
    status = models.CharField(max_length=10, blank=True, null=True)
    loan_premium = models.IntegerField(blank=True, null=True)
    fcrm = models.CharField(max_length=1, blank=True, null=True)
    rider_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rider_benefit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    prorated_prem = models.BigIntegerField(blank=True, null=True)
    next_annual_prem = models.BigIntegerField(blank=True, null=True)
    new_uw_year = models.IntegerField(blank=True, null=True)
    topup_amount = models.BigIntegerField(blank=True, null=True)
    paid_amount = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    interest_basis = models.CharField(max_length=1, blank=True, null=True)
    topup = models.CharField(max_length=1, blank=True, null=True)
    mod_factor = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    paid = models.CharField(max_length=1, blank=True, null=True)
    crm_flag = models.CharField(max_length=1, blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glmploan'


class Glrdrate(models.Model):
    rider_code = models.IntegerField(blank=True, null=True)
    rate = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    filler = models.CharField(max_length=54, blank=True, null=True)
    joint_rate = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)
    rate_spouse = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)
    rate_kid = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glrdrate'


class Glrates(models.Model):
    age = models.IntegerField(blank=True, null=True)
    ind_ratep = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    ind_rate = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)
    special_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    rate_band = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    age_band = models.BooleanField(blank=True, null=True)
    descr = models.CharField(max_length=7, blank=True, null=True)
    base = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    user_1 = models.CharField(max_length=42, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glrates'


class Premrates(models.Model):
    age = models.IntegerField(blank=True, null=True)
    loan_term = models.IntegerField(blank=True, null=True)
    premium_rate = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)
    bank_code = models.IntegerField(blank=True, null=True)
    joint_rate = models.DecimalField(max_digits=20, decimal_places=8, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'premrates'


class Glcrhealthq(models.Model):
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    member_no = models.IntegerField(blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    loan_no = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    q1 = models.CharField(max_length=1, blank=True, null=True)
    q1description = models.CharField(max_length=100, blank=True, null=True)
    q2 = models.CharField(max_length=1, blank=True, null=True)
    q2description = models.CharField(max_length=100, blank=True, null=True)
    q3 = models.CharField(max_length=1, blank=True, null=True)
    q3description = models.CharField(max_length=100, blank=True, null=True)
    q4 = models.CharField(max_length=1, blank=True, null=True)
    q4description = models.CharField(max_length=100, blank=True, null=True)
    q5 = models.CharField(max_length=1, blank=True, null=True)
    q5description = models.CharField(max_length=100, blank=True, null=True)
    q6 = models.CharField(max_length=1, blank=True, null=True)
    q6description = models.CharField(max_length=100, blank=True, null=True)
    q7 = models.CharField(max_length=1, blank=True, null=True)
    q7description = models.CharField(max_length=100, blank=True, null=True)
    q8 = models.CharField(max_length=1, blank=True, null=True)
    q8description = models.CharField(max_length=100, blank=True, null=True)
    q9 = models.CharField(max_length=1, blank=True, null=True)
    q9description = models.CharField(max_length=100, blank=True, null=True)
    q10 = models.CharField(max_length=1, blank=True, null=True)
    q10description = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glcrhealthq'


class Gljointmst(models.Model):
    client_no = models.CharField(primary_key=True,max_length=8)
    account_no = models.CharField(max_length=12, blank=True, null=True)
    loan_no = models.IntegerField(blank=True, null=True)
    policy_no = models.CharField(max_length=9, blank=True, null=True)
    status = models.BooleanField(blank=True, null=True)
    commence_date = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    marital_sta = models.CharField(max_length=1, blank=True, null=True)
    other_names = models.CharField(max_length=20, blank=True, null=True)
    surname = models.CharField(max_length=15, blank=True, null=True)
    title = models.CharField(max_length=4, blank=True, null=True)
    user1 = models.CharField(max_length=29, blank=True, null=True)
    principle_m = models.CharField(max_length=8, blank=True, null=True)
    loan_amount = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'gljointmst'


class Glscheme(models.Model):
    policy_no = models.CharField(max_length=9, primary_key=True)
    pol_class = models.CharField(max_length=3, blank=True, null=True)
    scheme_type = models.CharField(max_length=3, blank=True, null=True)
    type = models.CharField(max_length=1, blank=True, null=True)
    registration = models.CharField(max_length=1, blank=True, null=True)
    pol_number = models.IntegerField(blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    scheme_name = models.CharField(max_length=200, blank=True, null=True)
    profit_sharing = models.CharField(max_length=1, blank=True, null=True)
    pay_freq_ta = models.CharField(max_length=1, blank=True, null=True)
    pay_freq_da = models.CharField(max_length=1, blank=True, null=True)
    with_discount_ind = models.CharField(max_length=1, blank=True, null=True)
    with_rider = models.CharField(max_length=1, blank=True, null=True)
    renewal_mkr = models.BooleanField(blank=True, null=True)
    total_members2 = models.IntegerField(blank=True, null=True)
    commence_year = models.CharField(max_length=4, blank=True, null=True)
    commence_month = models.CharField(max_length=2, blank=True, null=True)
    commence_day = models.CharField(max_length=2, blank=True, null=True)
    renewal_year = models.CharField(max_length=4, blank=True, null=True)
    renewal_month = models.CharField(max_length=2, blank=True, null=True)
    renewal_day = models.CharField(max_length=2, blank=True, null=True)
    total_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_annual_salary = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    average_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    free_cover_limit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    discount_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    branch = models.IntegerField(blank=True, null=True)
    agent = models.IntegerField(blank=True, null=True)
    reass_code = models.BooleanField(blank=True, null=True)
    maturity_date = models.DateField(blank=True, null=True)
    comm_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    pay_mode = models.CharField(max_length=1, blank=True, null=True)
    coy_pension_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    emp_pension_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    pension_years = models.IntegerField(blank=True, null=True)
    unit_rates_app = models.CharField(max_length=1, blank=True, null=True)
    unit_rate = models.DecimalField(max_digits=13, decimal_places=6, blank=True, null=True)
    unit_rate_change_app = models.CharField(max_length=1, blank=True, null=True)
    gross_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    single_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    period_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    nett_premium_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    nett_premium_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    nett_premium_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_factor = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    status = models.BooleanField(blank=True, null=True)
    max_sum_ass_ind = models.CharField(max_length=1, blank=True, null=True)
    max_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    market_segment = models.CharField(max_length=2, blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    profit_share_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_reass_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    salary_ind = models.CharField(max_length=1, blank=True, null=True)
    profit_share_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    costing_type = models.CharField(max_length=1, blank=True, null=True)
    force_change = models.CharField(max_length=1, blank=True, null=True)
    rate_type = models.CharField(max_length=1, blank=True, null=True)
    gurantee_period = models.IntegerField(blank=True, null=True)
    reass_per = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    retention_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    salary_esc = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    males = models.IntegerField(blank=True, null=True)
    females = models.IntegerField(blank=True, null=True)
    filler1 = models.CharField(max_length=1, blank=True, null=True)
    ndf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    funding_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    ass_int_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    retire_age = models.IntegerField(blank=True, null=True)
    nrd = models.IntegerField(blank=True, null=True)
    nrd_f = models.IntegerField(blank=True, null=True)
    admin_charge = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    admin_included = models.CharField(max_length=1, blank=True, null=True)
    total_target_pension = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_lump_summ = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    pension_esc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    voluntary_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    vol_contrib_coy = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vol_contrib_emp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    service_ind = models.CharField(max_length=1, blank=True, null=True)
    factor = models.IntegerField(blank=True, null=True)
    term_years = models.IntegerField(blank=True, null=True)
    total_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_pension_emp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_pension_coy = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    nssf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_death_claim = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    co_retention = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    mandatory_share = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_share = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ave_target_sal_yrs = models.IntegerField(blank=True, null=True)
    prem_paid_date = models.DateField(blank=True, null=True)
    medical_extra = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    contrib_as_net_prem_ind = models.CharField(max_length=1, blank=True, null=True)
    with_other_cover_ind = models.CharField(max_length=1, blank=True, null=True)
    nssf_ind = models.CharField(max_length=1, blank=True, null=True)
    contrib_after_retirement_ind = models.CharField(max_length=1, blank=True, null=True)
    period_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    with_ophans_contrib_ind = models.CharField(max_length=1, blank=True, null=True)
    with_widows_contrib_ind = models.CharField(max_length=1, blank=True, null=True)
    br_ind = models.CharField(max_length=1, blank=True, null=True)
    with_categ_ind = models.CharField(max_length=1, blank=True, null=True)
    doc_code = models.CharField(max_length=8, blank=True, null=True)
    prem_3q_ind = models.CharField(max_length=1, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    fcl_change_app = models.CharField(max_length=1, blank=True, null=True)
    with_interest_ind = models.CharField(max_length=1, blank=True, null=True)
    facult_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    categ_ind = models.CharField(max_length=1, blank=True, null=True)
    period_from = models.DateField(blank=True, null=True)
    period_to = models.DateField(blank=True, null=True)
    pre_post = models.CharField(max_length=1, blank=True, null=True)
    total_target_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_loans = models.IntegerField(blank=True, null=True)
    paid_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    old_policy_number = models.CharField(max_length=19, blank=True, null=True)
    other_policy_uw_year = models.IntegerField(blank=True, null=True)
    other_policy_no = models.CharField(max_length=9, blank=True, null=True)
    with_life_cover_ind = models.CharField(max_length=1, blank=True, null=True)
    last_unit_rate_age = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    treaty_code = models.CharField(max_length=1, blank=True, null=True)
    mandatory_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_share_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    reass_remarks = models.CharField(max_length=30, blank=True, null=True)
    without_salary_ind = models.CharField(max_length=1, blank=True, null=True)
    without_salary_sa = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    fixed_fcl = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    debited_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    balance_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ytd_balance = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ophans_contrib_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    widows_contrib_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    da_type = models.CharField(max_length=2, blank=True, null=True)
    claims_exp_from = models.IntegerField(blank=True, null=True)
    claims_exp_to = models.IntegerField(blank=True, null=True)
    profit_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    profit_loss = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    claims_premium_ratio = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    profit_allowance = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    commission_loading = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    unit_rate_discount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    phi_flag = models.CharField(max_length=1, blank=True, null=True)
    waiting_period = models.DecimalField(max_digits=2, decimal_places=2, blank=True, null=True)
    salary_benefit_1 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    salary_benefit_2 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    salary_benefit_3 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    profit_premium_paid = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    profit_claims_paid = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    claims_premium_increase = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_norm_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_max_age = models.IntegerField(blank=True, null=True)
    lc_extra_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_min_age = models.IntegerField(blank=True, null=True)
    credit_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    filler3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    claims_paid = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    jv_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    pens_allow_ind = models.CharField(max_length=1, blank=True, null=True)
    total_coy_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    loading_factor_ind = models.CharField(max_length=1, blank=True, null=True)
    loading_factor_per = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    currency = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    currency_rate = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vat_rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    fac_cessn = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    co_prem_retention = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    epg = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    min_sa_ind = models.CharField(max_length=1, blank=True, null=True)
    min_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    admin_amount = models.DecimalField(max_digits=20, decimal_places=4, blank=True, null=True)
    risk_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_comm_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_comm_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_lump_sum = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    hiv_limit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    reass_comm_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    refer_name = models.CharField(max_length=24, blank=True, null=True)
    death_claims = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    new_entrant = models.IntegerField(blank=True, null=True)
    total_lump_sumf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_sd_amount = models.IntegerField(blank=True, null=True)
    quota_sd_amount = models.IntegerField(blank=True, null=True)
    merc_policy_no = models.CharField(max_length=9, blank=True, null=True)
    client_n = models.IntegerField(blank=True, null=True)
    max_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    bank_code = models.IntegerField(blank=True, null=True)
    created_by = models.CharField(max_length=15, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)
    modified_by = models.CharField(max_length=15, blank=True, null=True)
    modified_date = models.DateField(blank=True, null=True)
    total_members = models.IntegerField(blank=True, null=True)
    savings_yn = models.CharField(max_length=1, blank=True, null=True)
    ppd_yn = models.CharField(max_length=1, blank=True, null=True)
    loss_of_rev_yn = models.CharField(max_length=1, blank=True, null=True)
    mp_insurance = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    esc_freq = models.IntegerField(blank=True, null=True)
    esc_factor = models.IntegerField(blank=True, null=True)
    admin_charge_term = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    comm_rate_term = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    uw_year_from = models.IntegerField(blank=True, null=True)
    uw_month_from = models.IntegerField(blank=True, null=True)
    uw_year_to = models.IntegerField(blank=True, null=True)
    uw_month_to = models.IntegerField(blank=True, null=True)
    mod_factor = models.DecimalField(max_digits=15, decimal_places=6, blank=True, null=True)
    filler = models.CharField(max_length=925, blank=True, null=True)
    ren_type = models.CharField(max_length=1, blank=True, null=True)
    tl_code = models.CharField(max_length=5, blank=True, null=True)
    j_unit_rate = models.DecimalField(max_digits=13, decimal_places=6, blank=True, null=True)
    load_flag = models.CharField(max_length=1, blank=True, null=True)
    susp_glhead = models.CharField(max_length=9, blank=True, null=True)
    susp_glhead_sage = models.CharField(max_length=9, blank=True, null=True)
    aims_ledger = models.CharField(max_length=10, blank=True, null=True)
    sage_ledger = models.CharField(max_length=10, blank=True, null=True)
    sage_sub_ledger = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glscheme'


class Glmmast(models.Model):
    policy_no = models.CharField(max_length=9, primary_key=True)
    member_no = models.IntegerField(blank=True, null=True)
    uw_year = models.IntegerField(blank=True, null=True)
    client_no = models.CharField(max_length=8, blank=True, null=True)
    scheme_type = models.CharField(max_length=3, blank=True, null=True)
    surname = models.CharField(max_length=15, blank=True, null=True)
    other_names = models.CharField(max_length=20, blank=True, null=True)
    title = models.CharField(max_length=4, blank=True, null=True)
    birth_year = models.CharField(max_length=4, blank=True, null=True)
    birth_month = models.CharField(max_length=2, blank=True, null=True)
    birth_day = models.CharField(max_length=2, blank=True, null=True)
    uw_date = models.DateField(blank=True, null=True)
    payroll_no = models.CharField(max_length=10, blank=True, null=True)
    commence_year = models.CharField(max_length=4, blank=True, null=True)
    commence_month = models.CharField(max_length=2, blank=True, null=True)
    commence_day = models.CharField(max_length=2, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    marital_sta = models.CharField(max_length=1, blank=True, null=True)
    nssf_app = models.CharField(max_length=1, blank=True, null=True)
    renewal_mkr = models.BooleanField(blank=True, null=True)
    status = models.BooleanField(blank=True, null=True)
    uw_ind = models.CharField(max_length=1, blank=True, null=True)
    acceptance_terms_issued = models.CharField(max_length=1, blank=True, null=True)
    mem_cert_ind = models.CharField(max_length=1, blank=True, null=True)
    evidence_age = models.CharField(max_length=1, blank=True, null=True)
    category = models.CharField(max_length=1, blank=True, null=True)
    medical_req = models.CharField(max_length=1, blank=True, null=True)
    app_form_ind = models.CharField(max_length=1, blank=True, null=True)
    emp_decl_ind = models.CharField(max_length=1, blank=True, null=True)
    branch_no = models.CharField(max_length=2, blank=True, null=True)
    uw_decision = models.IntegerField(blank=True, null=True)
    nrd = models.IntegerField(blank=True, null=True)
    annual_prem_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    term_years = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    current_salary = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    coy_pension = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    emp_pension = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    retire_date = models.DateField(blank=True, null=True)
    nett_deposit_fund = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    life_cover_factor = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    lc_norm_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_total_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_extra_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rating_code = models.IntegerField(blank=True, null=True)
    orig_sum_insured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    maturity_date = models.DateField(blank=True, null=True)
    dola = models.DateField(blank=True, null=True)
    co_risk_retention = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    co_prem_retention = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    co_reass_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mandatory_share = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    mandatory_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    mandatory_share_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mandatory_comm_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    mandatory_comm_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_share = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_share_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_share_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    quota_comm_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    quota_comm_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_amount_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_premium_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_rate_1 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_rate_2 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_rate_3 = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    surplus_comm_rate_1 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    surplus_comm_rate_2 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    surplus_comm_rate_3 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_comm_amt_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    target_salary = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    est_lump_sum = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    funding_balance = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    employee_per = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    employer_per = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    nssf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    joined_service = models.DateField(blank=True, null=True)
    single_prem_coy = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    epg = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    single_prem_emp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vol_contrib_per = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    vol_contrib_emp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    date_last_prem_paid = models.DateField(blank=True, null=True)
    vol_contrib_coy = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    past_service = models.IntegerField(blank=True, null=True)
    future_service = models.IntegerField(blank=True, null=True)
    target_pension = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    contrib_fact = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    date_joined = models.DateField(blank=True, null=True)
    ave_of_target_sal = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    net_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    annual_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    emp_admin = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    coy_admin = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    mandatory_dr_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_dr_prem_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_dr_prem_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_dr_prem_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_dr_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_dr_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    retention_dr_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_comm_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    emp_pens_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    coy_pens_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    other_retention = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    new_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    lc_new_annual_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    emp_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    coy_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_pension = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    target_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ta_status = models.BooleanField(blank=True, null=True)
    da_status = models.BooleanField(blank=True, null=True)
    loans_granted = models.IntegerField(blank=True, null=True)
    rider_benefit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    rider_premium = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    base = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    acceptance_terms = models.CharField(max_length=20, blank=True, null=True)
    date_left = models.DateField(blank=True, null=True)
    fill1 = models.CharField(max_length=1, blank=True, null=True)
    old_pol_no = models.CharField(max_length=19, blank=True, null=True)
    mem_no = models.IntegerField(blank=True, null=True)
    rest_no = models.CharField(max_length=4, blank=True, null=True)
    conf_uw_year = models.IntegerField(blank=True, null=True)
    unit_rate_age_ind = models.BooleanField(blank=True, null=True)
    phi_flag = models.CharField(max_length=1, blank=True, null=True)
    lc_supp_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    sum_assured_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    medical_uw_loading = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    restricted_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    mandatory_extra_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    retention_extra_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    quota_extra_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_extra_prem_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_extra_prem_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    surplus_extra_prem_3 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_extra_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    last_accepted_flag = models.CharField(max_length=1, blank=True, null=True)
    prev_uw_sum_assured = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    pens_allowances = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    widows_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ophans_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    pension_as_perc_of_sal = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    phi_total_contrib = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_total_benefits = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_waiver = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_life_cover_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_pension_contrib_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_waiver_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_balance_flag = models.CharField(max_length=1, blank=True, null=True)
    phi_salary_benefit_bf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    phi_salary_benefit = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    facult_comm_rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    facult_comm_amt = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    user_str = models.CharField(max_length=20, blank=True, null=True)
    co_extra_prem = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    pol_fund = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    age_treaty = models.IntegerField(blank=True, null=True)
    category_lc = models.CharField(max_length=1, blank=True, null=True)
    limit_flag = models.CharField(max_length=1, blank=True, null=True)
    occupation = models.CharField(max_length=30, blank=True, null=True)
    premiums_paid_this_year = models.IntegerField(blank=True, null=True)
    accum_value = models.BigIntegerField(blank=True, null=True)
    sa_limit = models.BigIntegerField(blank=True, null=True)
    id_no = models.CharField(max_length=8, blank=True, null=True)
    last_salary = models.IntegerField(blank=True, null=True)
    loaded_premium = models.IntegerField(blank=True, null=True)
    quota_co_ret = models.BigIntegerField(blank=True, null=True)
    refer_name = models.CharField(max_length=24, blank=True, null=True)
    merc_policy_no = models.CharField(max_length=9, blank=True, null=True)
    dept_no = models.IntegerField(blank=True, null=True)
    client_n = models.IntegerField(blank=True, null=True)
    client_name = models.CharField(max_length=48, blank=True, null=True)
    account_year = models.IntegerField(blank=True, null=True)
    account_month = models.IntegerField(blank=True, null=True)
    comm_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    form_serial = models.CharField(max_length=13, blank=True, null=True)
    created_by = models.CharField(max_length=15, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)
    modified_by = models.CharField(max_length=15, blank=True, null=True)
    modified_date = models.DateField(blank=True, null=True)
    telephone = models.CharField(max_length=15, blank=True, null=True)
    term_of_savings = models.IntegerField(blank=True, null=True)
    ppd_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    ppd_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_of_rev_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    loss_of_rev_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    savings_amt = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    savings_prem = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    sum_assured = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    sn_no = models.IntegerField(blank=True, null=True)
    sn_no1 = models.CharField(max_length=11, blank=True, null=True)
    li_no = models.IntegerField(blank=True, null=True)
    li_no1 = models.CharField(max_length=12, blank=True, null=True)
    canc_reason = models.CharField(max_length=20, blank=True, null=True)
    pay_md = models.CharField(max_length=6, blank=True, null=True)
    filler = models.CharField(max_length=577, blank=True, null=True)
    fcrm = models.CharField(max_length=1, blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    renewal_date = models.DateField(blank=True, null=True)
    est_loan_amount = models.BigIntegerField(blank=True, null=True)
    top_member_no = models.IntegerField(blank=True, null=True)
    cancel_mem = models.CharField(max_length=1, blank=True, null=True)
    topup = models.CharField(max_length=1, blank=True, null=True)
    period_from = models.DateField(blank=True, null=True)
    period_to = models.DateField(blank=True, null=True)
    batch_no = models.CharField(max_length=8, blank=True, null=True)
    retrenchment = models.CharField(max_length=1, blank=True, null=True)
    retrench_period = models.IntegerField(blank=True, null=True)
    comm_rate = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glmmast'

class Maxserials(models.Model):
    starts_with = models.CharField(max_length=2, primary_key=True)
    max_serail = models.CharField(max_length=6, blank=True, null=True)

    class Meta:
        managed = False  # Created from a view. Don't remove.
        db_table = 'maxserials'
